### ISSUE TITLE
Question: what is the role of the runs argument of Simulation.__init__

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#223]
I suspect it is for multiple simulations but I do not see any real use of it.
I would interested to help to allow liam to produce the same simulation n times with different seeds.
I am just writing ugly wrappers right now but if you have a clear understanding on how to do that, i a m eager to listen and try to help ;-)

**Comment by gdementen** [comment]
You suspect correctly :). This was an embryonic feature that I started to implement but ran out of time, so instead of throwing what I had away I committed it even if it wasn't really functional/useful. Honestly, I don't remember what it would take to make it useful. FWIW, the issue for this is #193. I'll add a few comments there.
