### ISSUE TITLE
Troubles while accessing element in tables

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#292]
I have trouble while accessing tables resulting in a table populated, (sometimes totally see test2d, other times here and there see test3d)  with `nan` values.

Everything is in the following zip [ecm_liam2.zip](https://github.com/liam2/liam2/files/2557486/ecm_liam2.zip)
Just unzip and run
```
liam2 import import.yml
liam2 run console.yml
```
Any hint @gdementen ?

cc @benbel

**Comment by gdementen** [comment]
which version of liam2 is this running on? master?

**Comment by benjello** [comment]
Yep running on master.

**Comment by gdementen** [comment]
I get:

ValueError: [0, 1] is ambiguous (valid in a, b)
when evaluating: assertEqual(test_3d[[0, 1]], [[0, 1]])

which seems perfectly normal given the labels on test_3d axes.

Two (probably related) notes though:


   - I had to change console.yml to read:

globals:
    test_2d:
      type: int
    test_3d:
      type: float

to make it load the globals successfully (otherwise I had Exception:
Field type for 'test_2d' in hdf5 input file is 'int' instead of
'float')


   - test_2d does not contain any NaN here (and I don't see why it should).
   Here is the output of "run console.yml":


 test_3d: a  b\c    1    2
0    0  2.0  3.0
0    1  nan  nan
1    0  nan  nan
1    1  4.0  3.0
2    0  2.0  3.0
2    1  nan  nan
3    0  nan  nan
3    1  4.0  3.0
 a\b  1  2
  0  0  3
  1  4  3
 a\b  2
  0  3 Traceback (most recent call last):


What version of larray are you using? Could you run liam2 --version and
give me the results?

Thanks

**Comment by gdementen** [comment]
> Sorry @gdementen, I should have messed up something (bad install). I do obtain the same result as you after some manipulations. Still I have the following questions/problems:
> 
>     * I do not understand why the NaNs populate test_3d. Does it assume some indexing.

This is because larray currently only supports dense arrays (i.e. arrays with all combinations of all axes labels present), so it extends any array given to it to be dense, filling missing values with nan.
 
>     * When I have ambiguous labels as in test_2d, I tried the X.b notation after having read the `larray` doc but it didn't work and produced

Yes, this is not implemented yet in liam2. This is one of the most important point to resolve before 0.13. I have to think what's best in liam2. The easiest for me would indeed to add the special X variable to liam2 namespace, but I think we can do better in the context of liam2. For example, I think that:
  test_2D[0, b=1]
would be more readable, but I am not sure I can do it easily and I haven't had time to dive into this yet.

**Comment by gdementen** [comment]
by the way, you could try using:
```python
test_2D[0, 'b[1]']
```
That **might** work. At least it would in pure larray. I haven't touched the liam2 integration of it for too long to know whether it will work in liam2 or not.

**Comment by gdementen** [comment]
Closing this as there isn't anything new to do. See #275 for the ambiguous labels thing.
