### ISSUE TITLE
Matching children with mothers (immigrants)

### ISSUE THREAD

**Issue by RiccardoContiSogei** [liam2/liam2#331]
Hello,
I am experimenting with a 'synthetic' migration module. Each year individuals are 'born' within the model and carry characteristics in terms of age, gender, education and country of origin according to immigration forecasts. After the newly immigrated individuals are created, they need to be organized in households. According to country of origin, a portion of them is coupled using the matching function.

Once that is done, I am left with a number of underage individuals that I would like to match with adult females (mothers) and their partners (by same country of origin). I thought of using the 'matching' function for this as well.
The only controls I would like to impose are: i) the absolute age difference between mother and child is between 18 and 40; ii) some mothers can have more than 1 child.
I can do the latter by running the process on a quota of children at a time. Any suggestions on how to solve the former? Can I substitute the 'score' portion with a boolean condition?

Thank you all very much,
Riccardo

**Comment by gdementen** [comment]
For what it's worth, I prefer when usage questions are sent to the liam2-users mailing list, as mentioned on https://liam2.plan.be/pages/contact.html. In the end, I am the one answering most questions anyway but at least on the mailing list the answer is seen by more people. Github issues are preferably used for bugs or new feature suggestions (potentially after some discussion on the -users list).

That said, in this case, I think you can use a boolean condition as the score but it will still be interpreted as a score (i.e. 0 or 1) and you cannot have a condition preventing a match in all case. However, what you can do is craft your score expressions so that it gives a very low score (negative value or something like that) for the matches you don't want to happen. In that case, those matches can still happen but will only happen after all the "good" matches are exhausted.

I hope it helps...
